spring:
  application:
    name: spring-batch-study
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
#  datasource:
#    url: jdbc:mariadb://localhost:3306
#    username: root
#    password: 1234
#    driver-class-name: org.mariadb.jdbc.Driver
#  batch:
#    jdbc:
#      initialize-schema: always
  h2:
    console:
      enabled: true
      path: /h2-console